userx@user:~/Documents/linux-monitoring$ cd prometheus
userx@user:~/Documents/linux-monitoring/prometheus$ ls
beginning          consoles  NOTICE      prometheus.yml  README.md   tasks_2.md
console_libraries  LICENSE   prometheus  promtool        tasks_1.md  Шпаргалка.md
userx@user:~/Documents/linux-monitoring/prometheus$ nano prometheus.yml
  GNU nano 7.2                                                  prometheus.yml
# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]
